services:
  - type: web
    name: nairon-auth-api
    branch: develop
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_UNPOOLED
        sync: false
      - key: JWT_SECRET
        sync: false
